// Code generated by MockGen. DO NOT EDIT.
// Source: ya_azs.go

// Package ya_azs is a generated GoMock package.
package ya_azs

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockYaAzsRepository is a mock of YaAzsRepository interface.
type MockYaAzsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockYaAzsRepositoryMockRecorder
}

// MockYaAzsRepositoryMockRecorder is the mock recorder for MockYaAzsRepository.
type MockYaAzsRepositoryMockRecorder struct {
	mock *MockYaAzsRepository
}

// NewMockYaAzsRepository creates a new mock instance.
func NewMockYaAzsRepository(ctrl *gomock.Controller) *MockYaAzsRepository {
	mock := &MockYaAzsRepository{ctrl: ctrl}
	mock.recorder = &MockYaAzsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYaAzsRepository) EXPECT() *MockYaAzsRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockYaAzsRepository) Add(ctx context.Context, idAzs int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, idAzs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockYaAzsRepositoryMockRecorder) Add(ctx, idAzs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockYaAzsRepository)(nil).Add), ctx, idAzs)
}

// CreateTable mocks base method.
func (m *MockYaAzsRepository) CreateTable(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockYaAzsRepositoryMockRecorder) CreateTable(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockYaAzsRepository)(nil).CreateTable), ctx)
}

// Delete mocks base method.
func (m *MockYaAzsRepository) Delete(ctx context.Context, idAzs int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, idAzs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockYaAzsRepositoryMockRecorder) Delete(ctx, idAzs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockYaAzsRepository)(nil).Delete), ctx, idAzs)
}

// DeleteTable mocks base method.
func (m *MockYaAzsRepository) DeleteTable(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTable", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTable indicates an expected call of DeleteTable.
func (mr *MockYaAzsRepositoryMockRecorder) DeleteTable(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTable", reflect.TypeOf((*MockYaAzsRepository)(nil).DeleteTable), ctx)
}

// GetEnable mocks base method.
func (m *MockYaAzsRepository) GetEnable(ctx context.Context, idAzs int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnable", ctx, idAzs)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnable indicates an expected call of GetEnable.
func (mr *MockYaAzsRepositoryMockRecorder) GetEnable(ctx, idAzs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnable", reflect.TypeOf((*MockYaAzsRepository)(nil).GetEnable), ctx, idAzs)
}

// GetEnableAll mocks base method.
func (m *MockYaAzsRepository) GetEnableAll(ctx context.Context) ([]Station, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnableAll", ctx)
	ret0, _ := ret[0].([]Station)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnableAll indicates an expected call of GetEnableAll.
func (mr *MockYaAzsRepositoryMockRecorder) GetEnableAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnableAll", reflect.TypeOf((*MockYaAzsRepository)(nil).GetEnableAll), ctx)
}

// GetEnableList mocks base method.
func (m *MockYaAzsRepository) GetEnableList(ctx context.Context) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnableList", ctx)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnableList indicates an expected call of GetEnableList.
func (mr *MockYaAzsRepositoryMockRecorder) GetEnableList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnableList", reflect.TypeOf((*MockYaAzsRepository)(nil).GetEnableList), ctx)
}

// GetLocation mocks base method.
func (m *MockYaAzsRepository) GetLocation(ctx context.Context, idAzs int) (Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocation", ctx, idAzs)
	ret0, _ := ret[0].(Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocation indicates an expected call of GetLocation.
func (mr *MockYaAzsRepositoryMockRecorder) GetLocation(ctx, idAzs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocation", reflect.TypeOf((*MockYaAzsRepository)(nil).GetLocation), ctx, idAzs)
}

// UpdateEnable mocks base method.
func (m *MockYaAzsRepository) UpdateEnable(ctx context.Context, idAzs int, isEnable bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnable", ctx, idAzs, isEnable)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEnable indicates an expected call of UpdateEnable.
func (mr *MockYaAzsRepositoryMockRecorder) UpdateEnable(ctx, idAzs, isEnable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnable", reflect.TypeOf((*MockYaAzsRepository)(nil).UpdateEnable), ctx, idAzs, isEnable)
}

// UpdateLocation mocks base method.
func (m *MockYaAzsRepository) UpdateLocation(ctx context.Context, idAzs int, location Location) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, idAzs, location)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockYaAzsRepositoryMockRecorder) UpdateLocation(ctx, idAzs, location interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockYaAzsRepository)(nil).UpdateLocation), ctx, idAzs, location)
}
