// Code generated by MockGen. DO NOT EDIT.
// Source: trbl_button.go

// Package trbl_button is a generated GoMock package.
package trbl_button

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTrblButtonRepository is a mock of TrblButtonRepository interface.
type MockTrblButtonRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrblButtonRepositoryMockRecorder
}

// MockTrblButtonRepositoryMockRecorder is the mock recorder for MockTrblButtonRepository.
type MockTrblButtonRepositoryMockRecorder struct {
	mock *MockTrblButtonRepository
}

// NewMockTrblButtonRepository creates a new mock instance.
func NewMockTrblButtonRepository(ctrl *gomock.Controller) *MockTrblButtonRepository {
	mock := &MockTrblButtonRepository{ctrl: ctrl}
	mock.recorder = &MockTrblButtonRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrblButtonRepository) EXPECT() *MockTrblButtonRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTrblButtonRepository) Add(ctx context.Context, id_azs int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, id_azs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockTrblButtonRepositoryMockRecorder) Add(ctx, id_azs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTrblButtonRepository)(nil).Add), ctx, id_azs)
}

// CreateTable mocks base method.
func (m *MockTrblButtonRepository) CreateTable(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockTrblButtonRepositoryMockRecorder) CreateTable(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockTrblButtonRepository)(nil).CreateTable), ctx)
}

// Delete mocks base method.
func (m *MockTrblButtonRepository) Delete(ctx context.Context, id_azs int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id_azs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTrblButtonRepositoryMockRecorder) Delete(ctx, id_azs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTrblButtonRepository)(nil).Delete), ctx, id_azs)
}

// DeleteTable mocks base method.
func (m *MockTrblButtonRepository) DeleteTable(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTable", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTable indicates an expected call of DeleteTable.
func (mr *MockTrblButtonRepositoryMockRecorder) DeleteTable(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTable", reflect.TypeOf((*MockTrblButtonRepository)(nil).DeleteTable), ctx)
}

// Get mocks base method.
func (m *MockTrblButtonRepository) Get(ctx context.Context, id_azs int) (LogButton, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id_azs)
	ret0, _ := ret[0].(LogButton)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTrblButtonRepositoryMockRecorder) Get(ctx, id_azs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTrblButtonRepository)(nil).Get), ctx, id_azs)
}

// GetAll mocks base method.
func (m *MockTrblButtonRepository) GetAll(ctx context.Context) ([]LogButton, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]LogButton)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTrblButtonRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTrblButtonRepository)(nil).GetAll), ctx)
}

// Update mocks base method.
func (m *MockTrblButtonRepository) Update(ctx context.Context, id_azs, download int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id_azs, download)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTrblButtonRepositoryMockRecorder) Update(ctx, id_azs, download interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTrblButtonRepository)(nil).Update), ctx, id_azs, download)
}
